# These are supported funding model platforms

github: Franklyzzm # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: Franklyzzm # Replace with a single Patreon username
open_collective: Franklyzzm # Replace with a single Open Collective username
ko_fi: Franklyzzm # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: franklyzzm.github.io # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: Franklyzzm # Replace with a single Liberapay username
issuehunt: Franklyzzm # Replace with a single IssueHunt username
otechie: Franklyzzm # Replace with a single Otechie username
custom: https://franklyzzm.github.io # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
